USE honkForSublet;

DELETE FROM User;
ALTER TABLE User AUTO_INCREMENT = 0;

DELETE FROM Posting;
ALTER TABLE Posting AUTO_INCREMENT = 0;

DELETE FROM PostingPhoto;
ALTER TABLE PostingPhoto AUTO_INCREMENT = 0;

DELETE FROM AddressOf;